import type { ColumnDefinition, LeadFilters } from './types';
import {
  SPRING_STATUS_TO_PIPELINE,
  type PipelineTabStatus,
} from '@/lib/status';

export type { PipelineTabStatus };
export { SPRING_STATUS_TO_PIPELINE };

export const initialFilters: LeadFilters = {
  createdDate: '',
  insuranceFilterType: '',
  insuranceDateFilter: '',
  fitnessFilterType: '',
  fitnessDateFilter: '',
  puccFilterType: '',
  puccDateFilter: '',
  vehicleType: '',
  classType: '',
  grossWeight: '',
  vehicleAge: '',
  manufacturer: '',
  model: '',
  bodyType: '',
  norms: '',
  rtoOffice: '',
  mobileNumber: '',
  searchMobileNumber: '',
  searchOwnerName: '',
  searchPanNumber: '',
  ownershipSerialNo: '',
  vehicleFinancer: '',
  customerType: '',
  pincode: '',
  pincodePermanentAddress: '',
  presentState: '',
  presentDistrict: '',
  permanentState: '',
  permanentDistrict: '',
  ownerAddressType: '',
  minVehicleCount: '',
  ownerCustomerType: '',
};

export const disabledFilterKeys: Array<keyof LeadFilters> = [
  'classType',
  'vehicleAge',
  'bodyType',
  'norms',
  'rtoOffice',
  'ownershipSerialNo',
  'vehicleFinancer',
  'presentState',
  'permanentState',
  'ownerAddressType',
];

export const tableColumns: ColumnDefinition[] = [
  { key: 'select', label: 'select' },
  { key: 'sNo', label: 'S.No' },
  { key: 'actions', label: 'Actions' },
  { key: 'vehicleRegNo', label: 'Vehicle Number' },
  { key: 'vehicleCategory', label: 'Vehicle Category' },
  { key: 'ownerName', label: 'Owner Name (full)' },
  { key: 'fatherName', label: "Father's Name" },
  { key: 'currentFullAddress', label: 'Current Full Address' },
  { key: 'mobileNo', label: 'RC Alternate Mobile No' },
  { key: 'panNumber', label: 'RC PAN No' },
  { key: 'totalTrips', label: 'Trips' },
  { key: 'totalMTWeight', label: 'GVW (Kgs)' },
  { key: 'make', label: 'Manufacturer' },
  { key: 'model', label: 'Model' },
  { key: 'status', label: 'Status' },
  { key: 'assignedExecutive', label: 'Leads Agent' },
  { key: 'customerType', label: 'Customer Type' },
  { key: 'updatedAt', label: 'Created' },
  { key: 'currentPincode', label: 'Current Pincode' },
  { key: 'currentDistrict', label: 'Current District' },
  { key: 'permanentFullAddress', label: 'Permanent Full Address' },
  { key: 'permanentPincode', label: 'Permanent Pincode' },
  { key: 'permanentDistrict', label: 'Permanent District' },
  { key: 'insuranceCompany', label: 'Insurance Company' },
  { key: 'insurancePolicyNo', label: 'Insurance Policy No.' },
  { key: 'insuranceDueDate', label: 'Ins. Due Date.' },
  { key: 'leadSource', label: 'Lead Source' },
  { key: 'permitValidUpto', label: 'Permit Valid Upto' },
  { key: 'fitnessValidUpto', label: 'Fitness Valid Upto' },
  { key: 'pollutionValidUpto', label: 'Pollution Valid Upto' },
  { key: 'panAddress', label: 'PAN Address' },
  { key: 'gstin', label: 'RC GSTIN' },
  { key: 'legalName', label: 'RC Legal Name' },
  { key: 'gstTradeName', label: 'RC GST Trade Name' },
  { key: 'gstContact', label: 'RC GST Contact' },
  { key: 'gstEmail', label: 'RC GST Email' },
  { key: 'khananPhone', label: 'Khanan Phone' },
];

export const tableFilterColumns: ColumnDefinition[] = [
  { key: 'vehicleRegNo', label: 'Vehicle Number' },
  { key: 'vehicleCategory', label: 'Vehicle Category' },
  { key: 'ownerName', label: 'Owner Name (full)' },
  { key: 'fatherName', label: "Father's Name" },
  { key: 'currentFullAddress', label: 'Current Full Address' },
  { key: 'mobileNo', label: 'RC Alternate Mobile No' },
  { key: 'panNumber', label: 'RC PAN No' },
  { key: 'make', label: 'Manufacturer' },
  { key: 'model', label: 'Model' },
  { key: 'status', label: 'Status' },
  { key: 'assignedExecutive', label: 'Leads Agent' },
  { key: 'customerType', label: 'Customer Type' },
  { key: 'totalTrips', label: 'Trips' },
  { key: 'totalMTWeight', label: 'GVW (Kgs)' },
  { key: 'updatedAt', label: 'Created' },
  { key: 'currentDistrict', label: 'Current District' },
  { key: 'permanentDistrict', label: 'Permanent District' },
  { key: 'currentPincode', label: 'Current Pincode' },
  { key: 'permanentPincode', label: 'Permanent Pincode' },
  { key: 'insuranceCompany', label: 'Insurance Company' },
  { key: 'insurancePolicyNo', label: 'Insurance Policy No.' },
  { key: 'leadSource', label: 'Lead Source' },
  { key: 'gstin', label: 'RC GSTIN' },
];

export const csvSchemaHeaders = [
  'select', 'S.No', 'Actions', 'Vehicle Number', 'Vehicle Category', 'Owner Name (full)', "Father's Name",
  'Current Full Address', 'Current Pincode', 'Current District', 'Permanent Full Address', 'Permanent Pincode',
  'Permanent District', 'Insurance Company', 'Insurance Policy No.', 'Ins. Due Date.', 'GIC Days Left',
  'Manuf. Mon/Yr', 'Vehicle Age YY/MM', 'Vehicle Class', 'GVW (Kgs)', 'Customer Type', 'Status', 'Leads Agent',
  'Created', 'Lead Source', 'MV Tax Paid Upto', 'MV Tax Days Left', 'Permit Valid Upto', 'Permit Days Left',
  'Offence', 'Fitness Valid Upto', 'Fitness Days Left', 'Pollution Valid Upto', 'Pollution Days Left',
  'RC Alternate Mobile No', 'RC PAN No', 'PAN Address', 'RC GSTIN', 'RC Legal Name', 'RC GST Trade Name',
  'RC GST Contact', 'RC GST Email', 'Khanan Phone',
] as const;

export const cardColorByIndex: string[] = [
  'text-blue-400',
  'text-yellow-400',
  'text-red-500',
  'text-yellow-400',
  'text-red-500',
  'text-blue-500',
  'text-green-500',
  'text-violet-300',
];
