apiVersion: v1
kind: Namespace
metadata:
  name: vahan360-frontend
  labels:
    app.kubernetes.io/name: vahan360
    app.kubernetes.io/part-of: vahan360-frontend
    pod-security.kubernetes.io/enforce: baseline
---
apiVersion: v1
kind: Namespace
metadata:
  name: vahan360-backend
  labels:
    app.kubernetes.io/name: vahan360
    app.kubernetes.io/part-of: vahan360-backend
    pod-security.kubernetes.io/enforce: baseline
---
apiVersion: v1
kind: Namespace
metadata:
  name: vahan360-scraper
  labels:
    app.kubernetes.io/name: vahan360
    app.kubernetes.io/part-of: vahan360-scraper
    pod-security.kubernetes.io/enforce: baseline
