{{- if .Values.web.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vahan360.fullname" . }}-web
  labels:
    {{- include "vahan360.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.web.service.type }}
  selector:
    {{- include "vahan360.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: {{ .Values.web.service.port }}
      targetPort: http
      protocol: TCP
{{- end }}
